import React from 'react';
import {AbsoluteFill, Easing, Img, interpolate, staticFile, useCurrentFrame} from 'remotion';
import {C, FONT} from '../theme';
export {C, FONT};
export const ease = Easing.bezier(.22,1,.36,1);
export const smooth = Easing.bezier(.65,0,.25,1);
export const p = (f:number,a:number,b:number) => interpolate(f,[a,b],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp',easing:ease});
export const mix = (f:number,a:number,b:number,x:number,y:number) => x+(y-x)*p(f,a,b);
export const lerp = (f:number,frames:number[],values:number[])=>interpolate(f,frames,values,{extrapolateLeft:'clamp',extrapolateRight:'clamp',easing:smooth});
export const appear = (f:number,a:number,d=30) => ({opacity:p(f,a,a+d),transform:`translateY(${(1-p(f,a,a+d))*28}px)`});
export const SHADOW='0 30px 95px -38px rgba(0,2,48,.28), 0 8px 28px -14px rgba(49,107,253,.12)';
export const DATA = {address:'ул. Нагорная, д. 20, корп. 4',material:'Штукатурная смесь фасадная, 25 кг',code:'ТМЦ-000263',basis:'ПСД-НГ-001',qty:'3 600',packs:'144',date:'08.10.2026'};

export const Base:React.FC<{children?:React.ReactNode;blue?:boolean;style?:React.CSSProperties}>=({children,blue=false,style})=><AbsoluteFill style={{fontFamily:FONT,color:blue?'white':C.ink,background:blue?C.blue:'#F3F5F9',overflow:'hidden',...style}}><AbsoluteFill style={{background:blue?'radial-gradient(ellipse at 65% 65%,#5d8dff50,transparent 65%)':'radial-gradient(ellipse 75% 90% at 60% 42%,#fff 0%,#eff3fb70 60%,transparent 100%)'}}/>{children}</AbsoluteFill>;

export const Brand:React.FC<{light?:boolean;label?:string}>=({light=false,label='Демонстрация прототипа'})=><><div style={{position:'absolute',left:86,top:48,display:'flex',alignItems:'center',gap:18,zIndex:50}}><Img src={staticFile('img/fkr-logo.png')} style={{width:126,filter:light?'brightness(0) invert(1)':'none'}}/></div><div style={{position:'absolute',right:86,top:58,fontSize:20,fontWeight:500,color:light?'#dbe6ff':C.muted,zIndex:50}}>{label}</div></>;

export const Icon:React.FC<{kind?:string;size?:number;color?:string}>=({kind='doc',size=28,color=C.blue})=><svg width={size} height={size} viewBox="0 0 32 32" fill="none">{kind==='search'?<><path d="M20.5 22.6a10.5 10.5 0 1 1 2.1-2.1l7 7-2.1 2.1-7-7ZM14 22a8 8 0 1 0 0-16 8 8 0 0 0 0 16Z" fill={color}/></>:kind==='check'?<path d="m5 16 7 7L28 7l-3-3-13 13-4-4-3 3Z" fill={color}/>:kind==='arrow'?<path d="M3 14h19l-7-7 3-3 12 12-12 12-3-3 7-7H3v-4Z" fill={color}/>:kind==='box'?<><path d="m16 2 13 7-13 7L3 9l13-7ZM3 12l11 6v13L3 25V12ZM18 18l11-6v13l-11 6V18Z" fill={color}/></>:kind==='building'?<><path d="M4 4h24v26H4V4Z" fill={color} opacity=".16"/><path d="M8 8h5v5H8V8Zm11 0h5v5h-5V8ZM8 17h5v5H8v-5Zm11 0h5v5h-5v-5ZM13 25h6v5h-6v-5Z" fill={color}/></>:kind==='time'?<><circle cx="16" cy="16" r="14" fill={color} opacity=".15"/><path d="M14 6h4v9l7 4-2 3-9-5V6Z" fill={color}/></>:<><path d="M6 2h13l7 7v21H6V2Z" fill={color} opacity=".15"/><path d="M18 2v9h8M10 16h12v3H10v-3Zm0 6h9v3h-9v-3Z" fill={color}/></>}</svg>;

export const Pill:React.FC<{children:React.ReactNode;tone?:'blue'|'orange'|'neutral';style?:React.CSSProperties}>=({children,tone='blue',style})=><span style={{display:'inline-flex',alignItems:'center',gap:9,padding:'10px 17px',borderRadius:13,fontSize:23,fontWeight:600,lineHeight:1.15,background:tone==='blue'?C.blue50:tone==='orange'?C.orange50:'#eff0f4',color:tone==='blue'?C.blue:tone==='orange'?'#BE561B':C.muted,...style}}>{children}</span>;

export const Panel:React.FC<{children:React.ReactNode;style?:React.CSSProperties}>=({children,style})=><div style={{background:'white',borderRadius:25,boxShadow:SHADOW,overflow:'hidden',...style}}>{children}</div>;

export const MaterialRow:React.FC<{qty?:string;packs?:boolean;active?:boolean;style?:React.CSSProperties;compact?:boolean}>=({qty=DATA.qty,packs=false,active=false,style,compact=false})=><div style={{display:'flex',alignItems:'center',gap:24,padding:compact?'22px 28px':'28px 32px',borderRadius:18,background:active?'linear-gradient(105deg,#edf3ff,#e4edff)':'#F5F6F9',...style}}><div style={{height:58,width:58,flexShrink:0,display:'grid',placeItems:'center',borderRadius:16,background:'white'}}><Icon kind="box" size={32}/></div><div style={{flex:1,minWidth:0}}><div style={{fontSize:compact?25:29,fontWeight:600,letterSpacing:-.55}}>{DATA.material}</div><div style={{fontSize:20,color:C.muted,marginTop:9}}>{DATA.code}</div></div><div style={{display:'flex',gap:10,alignItems:'baseline',paddingLeft:16,whiteSpace:'nowrap'}}><span style={{fontSize:compact?37:46,fontWeight:650,letterSpacing:-1.5,fontVariantNumeric:'tabular-nums'}}>{qty}</span><span style={{fontSize:23,color:C.muted}}>{packs?'пач.':'кг'}</span></div></div>;

export const Button:React.FC<{children:React.ReactNode;pressed?:number;secondary?:boolean;style?:React.CSSProperties}>=({children,pressed=0,secondary=false,style})=><div style={{display:'inline-flex',alignItems:'center',justifyContent:'center',gap:12,height:60,padding:'0 25px',fontSize:24,fontWeight:600,borderRadius:14,background:secondary?C.blue50:C.blue,color:secondary?C.blue:'white',boxShadow:secondary?'none':'0 9px 25px -13px #316bfd',transform:`scale(${1-pressed*.035})`,...style}}>{children}<Icon kind="arrow" size={22} color={secondary?C.blue:'white'}/></div>;

export type PointerKey=[number,number,number];
export const pointAt=(f:number,keys:PointerKey[])=>{let x=keys[0][1],y=keys[0][2];for(let i=0;i<keys.length-1;i++){const[a,x0,y0]=keys[i],[b,x1,y1]=keys[i+1];if(f>=b){x=x1;y=y1;continue;}if(f>=a){const k=interpolate(f,[a,b],[0,1],{easing:smooth,extrapolateLeft:'clamp',extrapolateRight:'clamp'});const len=Math.hypot(x1-x0,y1-y0)||1;const arc=Math.sin(k*Math.PI)*Math.min(35,len*.08);x=x0+(x1-x0)*k-(y1-y0)/len*arc;y=y0+(y1-y0)*k+(x1-x0)/len*arc;}break;}return{x,y};};
export const Pointer:React.FC<{frame?:number;keys:PointerKey[];clicks?:number[];visible?:[number,number];scale?:number}>=({frame,keys,clicks=[],visible=[0,10000],scale=1})=>{const local=useCurrentFrame(),f=frame??local;const {x,y}=pointAt(f,keys);const alpha=p(f,visible[0],visible[0]+12)*(1-p(f,visible[1]-12,visible[1]));let pressure=0;for(const c of clicks)pressure=Math.max(pressure,Math.max(0,1-Math.abs(f-c-2)/7));return <div style={{position:'absolute',inset:0,pointerEvents:'none',opacity:alpha,zIndex:100}}>{clicks.map(c=>{const d=f-c;if(d<0||d>30)return null;const q=pointAt(c,keys);return <div key={c} style={{position:'absolute',left:q.x-32,top:q.y-32,width:64,height:64,borderRadius:'50%',background:'radial-gradient(circle,#316bfd66, #316bfd00 72%)',transform:`scale(${.35+d/22})`,opacity:1-d/30}}/>;})}<div style={{position:'absolute',left:x,top:y,transform:`scale(${scale*(1-pressure*.18)})`,transformOrigin:'0 0',filter:'drop-shadow(0 4px 5px #00023044)'}}><svg width="34" height="43" viewBox="0 0 28 35"><path d="M3 2 25 21H14l6 11-6 3-6-12-5 8V2Z" fill="white"/><path d="M5 6 21 20H12l6 11-3 1-6-12-4 6V6Z" fill={C.ink}/></svg></div></div>;};

export const Title:React.FC<{children:React.ReactNode;sub?:string;style?:React.CSSProperties;frame?:number;at?:number}>=({children,sub,style,frame,at=0})=><div style={{position:'absolute',left:100,top:154,right:100,...(frame===undefined?{}:appear(frame,at)),...style}}><div style={{fontSize:76,lineHeight:1.06,letterSpacing:-3.7,fontWeight:650}}>{children}</div>{sub&&<div style={{fontSize:28,lineHeight:1.4,color:C.muted,marginTop:20,letterSpacing:-.25}}>{sub}</div>}</div>;
